# Generated by Django 5.1.5 on 2025-01-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Neptunian', 'Neptunian'), ('Terrestrials', 'Terrestrials'), ('Super Earths', 'Super Earths'), ('Gas Giants', 'Gas Giants')], default='', max_length=100),
        ),
    ]
