# Generated by Django 5.1.5 on 2025-02-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_alter_fotografia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
