# Generated by Django 5.1.5 on 2025-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_alter_fotografia_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
