# Generated by Django 5.1.5 on 2025-02-05 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_alter_fotografia_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='descricao',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
